#ifndef _SPI_CONFIG_H
#define _SPI_CONFIG_H


/**SPI_CLOCK_RATE:
 * OPTIONS:-
 * SPI_CLOCK_RATE_DIV_BY_2
 * SPI_CLOCK_RATE_DIV_BY_4  
 * SPI_CLOCK_RATE_DIV_BY_8  
 * SPI_CLOCK_RATE_DIV_BY_16
 * SPI_CLOCK_RATE_DIV_BY_32  
 * SPI_CLOCK_RATE_DIV_BY_64 
 * SPI_CLOCK_RATE_DIV_BY_128 
*/

#define SPI_CLOCK_RATE                 SPI_CLOCK_RATE_DIV_BY_2  

/**SPI_CLOCK_RATE:
 * OPTIONS:-
 * CLOCK_POLARITY_RISING_EDGE
 * CLOCK_POLARITY_FALLING_EDGE    
*/

#define CLOCK_POLARITY                 CLOCK_POLARITY_RISING_EDGE

/**SPI_CLOCK_RATE:
 * OPTIONS:-
 * CLOCK_PHASE_SAMPLE
 * CLOCK_PHASE_SETUP    
*/

#define CLOCK_PHASE                    CLOCK_PHASE_SAMPLE              



#endif