#ifndef _ADC_CONFIG_H
#define _ADC_CONFIG_H


/* ADC_PRESCALER_SELECT_VALUE
*  Options:
*  ADC_PRESCALER_DIV_BY_2
*  ADC_PRESCALER_DIV_BY_4
*  ADC_PRESCALER_DIV_BY_8
*  ADC_PRESCALER_DIV_BY_16
*  ADC_PRESCALER_DIV_BY_32
*  ADC_PRESCALER_DIV_BY_64
*  ADC_PRESCALER_DIV_BY_128
*/
#define ADC_PRESCALER_SELECT_VALUE                  ADC_PRESCALER_DIV_BY_64

/* ADC_REFERANCE_VOLTAGE_SELECT_VALUE
*  Options:
*  ADC_AREF_VOLTAGE
*  ADC_AVCC_VOLTAGE
*  ADC_INTERNAL_VOLTAGE
*/
#define ADC_REFERANCE_VOLTAGE_SELECT_VALUE          ADC_AVCC_VOLTAGE


/* ADC_RESULT_ADJUSTMENT SELECT
*  Options:
*  ACD_RIGHT_ADJUST
*  ACD_LEFT_ADJUST
*/
#define ADC_RESULT_ADJUSTMENT                       ACD_LEFT_ADJUST

#define ADC_MODE_SELECT                             ADC_SINGLE_CONVERSION_MODE
#endif